name: AppleMC-CommandSpy
author: ThatsNotLiam1337
version: 1.0
main: me.pm.commandspy.Main
description: Command Spy z discordem.
api-version: 1.13

commands:
  commandspyreload:
    description: reload configu
  broadcastdiscord:
    description: wiadomosc :D


permissions:
  pm.commandspy.log:
    default: op
  pm.commandspy.reload:
    default: op
  pm.commandspy.broadcast:
    default: op